package com.tapli.zaidimuparduotuve.mybatis.dao;

import com.tapli.zaidimuparduotuve.mybatis.model.Atsiliepimas;
import org.mybatis.cdi.Mapper;

import java.util.List;

@Mapper
public interface AtsiliepimasMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.ATSILIEPIMAS
     *
     * @mbg.generated Tue May 05  17:37:16 EEST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.ATSILIEPIMAS
     *
     * @mbg.generated Tue May 05  17:37:16 EEST 2022
     */
    int insert(Atsiliepimas record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.ATSILIEPIMAS
     *
     * @mbg.generated Tue May 05  17:37:16 EEST 2022
     */
    Atsiliepimas selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.ATSILIEPIMAS
     *
     * @mbg.generated Tue May 05  17:37:16 EEST 2022
     */
    List<Atsiliepimas> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.ATSILIEPIMAS
     *
     * @mbg.generated Tue May 05  17:37:16 EEST 2022
     */
    int updateByPrimaryKey(Atsiliepimas record);

    Atsiliepimas findOneByName(String atsiliepimoPavadinimas);
}