package com.tapli.zaidimuparduotuve.mybatis.dao;

import com.tapli.zaidimuparduotuve.mybatis.model.ZaidimoAtsiliepimas;
import org.mybatis.cdi.Mapper;

import java.util.List;

@Mapper
public interface ZaidimoAtsiliepimasMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.INSTRUMENTO_AKSESUARAS
     *
     * @mbg.generated Mon May 06 17:46:44 EEST 2022
     */
    int insert(ZaidimoAtsiliepimas record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.INSTRUMENTO_AKSESUARAS
     *
     * @mbg.generated Mon May 06 17:46:44 EEST 2022
     */
    List<ZaidimoAtsiliepimas> selectAll();
}