package com.tapli.zaidimuparduotuve.mybatis.model;

import lombok.Getter;
import lombok.Setter;

@Getter
@Setter
public class Atsiliepimas {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.ATSILIEPIMAS.ID
     *
     * @mbg.generated Tue May 05  17:37:16 EEST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.ATSILIEPIMAS.APRASYMAS
     *
     * @mbg.generated Tue May 05  17:37:16 EEST 2022
     */
    private String aprasymas;
}