package com.tapli.zaidimuparduotuve.mybatis.model;

import lombok.Getter;
import lombok.Setter;

@Getter
@Setter
public class ZaidimoAtsiliepimas {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.ZAIDIMO_ATSILIEPIMAS.ZAIDIMAI_ID
     *
     * @mbg.generated Mon May 06 17:46:44 EEST 2022
     */
    private Integer zaidimai_Id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.ZAIDIMO_ATSILIEPIMAS.ATSILIEPIMAI_ID
     *
     * @mbg.generated Mon May 06 17:46:44 EEST 2022
     */
    private Integer atsiliepimai_Id;
}